In this lesson, you created a middleware function called asyncWrapper. Why?
  I know that the asyncWrapper was created to wrap our CRUD functions and reduce the redundancy of the try/catch statment that previously wrapped our functions. I'm honestly not sure what the real benefit of using asyncWrapper is compared to try/catch block. They both wrap the controllers and they are both pretty readable.


Suppose that you want to make sure that both a status code and an error message are sent back to the user when they request the URL for a task that does not exist. Assume that youâ€™ve created a CustomAPIError class and an error handler that references that class. Complete the code:

const getTask = asyncWrapper(async (req, res, next) => {  
  const { id: taskID } = req.params;  
  const task = await Task.findOne({ _id: taskID });  
  if (!task) {  
    // your code here  
  }  
  res.status(200).json({ task });  
});  